### ISSUE TITLE
Commit to be Fit - gray background color

### ISSUE THREAD

**Issue by evt632** [LKMcManus/commit-to-be-fit#1]
The black against the gray is making it difficult to read

**Comment by evt632** [comment]
The drag and drop activity for heart and lung is a good placement for the drag and drop

**Comment by evt632** [comment]
I will come with a couple versions of style sheets with different colors for our site tomorrow.

I don't understand what is being asked of us here for the second part.

**Comment by dukyba** [comment]
The group liked the colors that Eric came up with. This is now being closed.
