### ISSUE TITLE
Links need more space

### ISSUE THREAD

**Issue by dukyba** [LKMcManus/commit-to-be-fit#11]
At this time the links are very crowded together especially on module 3, it makes it difficult to tell how many there are.  I imagine this would probably be changing when you determine the formatting anyway but just a heads up.

**Comment by evt632** [comment]
Added to CSS:

#navigation: "display:table;"

.navlinks
{
    display:table-cell;
    padding-top:5px;
}

Dustin, it should be ready to close now.

**Comment by dukyba** [comment]
This has been verified and will now be closed.
