### ISSUE TITLE
Module 4 - Setting New Goals

### ISSUE THREAD

**Issue by dukyba** [LKMcManus/commit-to-be-fit#111]
Attainable does not line up with the other words in the hover activity. I added an extra line break, but we will not know if this issue is fixed until we load up a new version in scormcloud.

**Comment by dukyba** [comment]
Will check with the last upload to scormcloud

**Comment by LKMcManus** [comment]
updated scormcloud 12/2, if this is corrected, it should be reflected.

**Comment by dukyba** [comment]
This is now fixed and ready to be closed.
