### ISSUE TITLE
Commit to 

### ISSUE THREAD

**Issue by LKMcManus** [LKMcManus/commit-to-be-fit#112]

**Comment by LKMcManus** [comment]
video goes off with narration, either mute video or set timer for it to go off after narration

**Comment by LKMcManus** [comment]
check on narrations related to videos

**Comment by evt632** [comment]
If I understand this correctly, they are saying that the video and the Narration are playing automatically at the same time. 

I am thinking this is a browser related issue or a user error, just like in issue 115.

I checked the HTML and there is no autoplay attribute set, and youtube should not play automatically.

I tried in Chrome and in FF  on Win 10 and could not make the video play automatically.

I have nothing else on this.

Ready to close.

**Comment by dukyba** [comment]
Closing
