### ISSUE TITLE
BMI and other Body info

### ISSUE THREAD

**Issue by LKMcManus** [LKMcManus/commit-to-be-fit#113]
In the caption; it is not printed:  "Click the link below to......".

**Comment by LKMcManus** [comment]
Cardio:  Common Exercises & Weekly recommendations:
Where the Cardiovascular Exercise:  throughout the day.  (Should be a period there.)

**Comment by LKMcManus** [comment]
Calories page:  In the caption area, go down to about the middle, and "Expend" is capitalized, but shouldn't be.

**Comment by LKMcManus** [comment]
I like that Dustin is wearing UTSA colors and showing the appropriate exercises.  Good job Dustin!

**Comment by LKMcManus** [comment]
Where it says to click here in the captions, probably would be better to state "Click on the 3-minute step test" on the page.  Because somebody who doesn't know much about the computer will continue to click on the caption to no avail.

**Comment by dukyba** [comment]
All issues have been addressed. At this point we are happy with the click here in the 3-minute step test. Closing
