### ISSUE TITLE
Plateaus?

### ISSUE THREAD

**Issue by LKMcManus** [LKMcManus/commit-to-be-fit#115]
Narration and video going on at the same time in the plateau section.

**Comment by LKMcManus** [comment]
Question 8 in the final exam.  After Never might be best to put a period.

**Comment by LKMcManus** [comment]
Question 8 in the final exam.  There is a star after the #2 answer.

**Comment by evt632** [comment]
Narration and video will play if user clicks to play the video before narration is done. 

I'm chalking that up to user error (If I am wrong, please let me know).

Question 8 looks good from the HTML side now.

Ready to close.

**Comment by dukyba** [comment]
Closing
