### ISSUE TITLE
Module 3 - length

### ISSUE THREAD

**Issue by evt632** [LKMcManus/commit-to-be-fit#13]
Module 3 is overwhelming and full of content.  The other modules don't seem daunting.  

Remember target audience - I feel that as someone who is overweight and interested in this topic, I wouldn't want to read so many articles just to find out how to commit to be fit.  It can be overwhelming just to read about the issues.  You don't want to lose your audience.

**Comment by mastersinsttech** [comment]
For future module 3 is actually our branching section so the user will choose one or the other and only see half of this content
