### ISSUE TITLE
Final Exam Question 2 - There is no A or B

### ISSUE THREAD

**Issue by evt632** [LKMcManus/commit-to-be-fit#131]
Consider rewording the answer selection.

![image](https://cloud.githubusercontent.com/assets/14190359/11581336/5fdcc724-9a06-11e5-9e5b-e5fa2a55d7d7.png)

**Comment by evt632** [comment]
Module 1 Checkpoint has the A, B, & C written in the answer portions. Consider removing those too?

![image](https://cloud.githubusercontent.com/assets/14190359/11581467/ee75f630-9a07-11e5-9ca0-61e4a21d12a9.png)

**Comment by LKMcManus** [comment]
I think this one is ready to close. I added A,B and C to question 2 but i'm not sure what youre saying needs to be changed on question 5

**Comment by evt632** [comment]
That works too.

Ready to close

**Comment by dukyba** [comment]
Done
