### ISSUE TITLE
Final Exam -  Question 8: Replace period with question mark.

### ISSUE THREAD

**Issue by evt632** [LKMcManus/commit-to-be-fit#134]
![image](https://cloud.githubusercontent.com/assets/14190359/11581384/e76a9e46-9a06-11e5-8071-9202e6986b13.png)

**Comment by evt632** [comment]
Also, add period to the first answer at the end of the second sentence.

**Comment by LKMcManus** [comment]
complete ready to close

**Comment by dukyba** [comment]
Done
