### ISSUE TITLE
Final Exam - Questions 1, 3, 7, & 9: All True/False questions should be formatted the same

### ISSUE THREAD

**Issue by evt632** [LKMcManus/commit-to-be-fit#135]
Questions 1, 7, & 9 do not begin with "True or False:"

I think Question 3 is the best example to prepare the learner for the type of question.

![image](https://cloud.githubusercontent.com/assets/14190359/11581422/6497317c-9a07-11e5-8783-18f2e288968d.png)

**Comment by LKMcManus** [comment]
complete ready to close

**Comment by dukyba** [comment]
Done
