### ISSUE TITLE
Is it ok that the Certificate has our name as "Last, First" ?

### ISSUE THREAD

**Issue by evt632** [LKMcManus/commit-to-be-fit#136]
To me, it does not look right.

![image](https://cloud.githubusercontent.com/assets/14190359/11581438/a5753a2c-9a07-11e5-909c-cef3d180dcae.png)

**Comment by wysiwyg98** [comment]
Updated code so the certificate displays first last name.  What is weird is last, first is how SCORM is passing the name.  "oScorm.get( "cmi.learner_name" )" is the code to pull the learner name from SCORM.  Ready to be closed.

**Comment by dukyba** [comment]
Done
