### ISSUE TITLE
Correction for Commit to Be Fit

### ISSUE THREAD

**Issue by dukyba** [LKMcManus/commit-to-be-fit#4]
Correction for Module 2/ Main Screen-
Under audio and captions, there is a spacing issue where the transcript is on the side instead of under the captions.  This issue seem to appear in all links except the checkpoint

Corrections for Module 3/ Cardio Checkpoint

There is no audio and captions

Corrections for Module 3/ Low Carb Checkpoint

There is no audio and captions

Under Module 4/ Assessment

There is no audio and captions

**Comment by dukyba** [comment]
There will not be Audio or Captions on the checkpoints. I am not able to recreate the issue with the spacing in module 2. Will verify with the rest of the team.

**Comment by evt632** [comment]
seems fine now
