### ISSUE TITLE
Cardio & Low Cal or Strength & Low Carb

### ISSUE THREAD

**Issue by evt632** [LKMcManus/commit-to-be-fit#61]
This section provided to much content to read. I suggest to limit and maybe provide a picture or some kind of graphic. Also, maybe limiting the caption as well.

**Comment by mastersinsttech** [comment]
It was a lot of content and was overwhelming.

**Comment by evt632** [comment]
Removed the content. Captions & audio will direct learners where to go.

RESOLVED

**Comment by dukyba** [comment]
Done
