### ISSUE TITLE
Intro page

### ISSUE THREAD

**Issue by evt632** [LKMcManus/commit-to-be-fit#62]
"Commit to Be Fit has the simple way for the average busy person with 10-40 pounds to**_?**_ have the body they want. "  _lose?_
Yes, the motto of eat less, move more, etc would be more effective if it were more of a symbol that was styled with color.
Enlarge the font of "Commit to be Fit" so it's more eye catching on the "Welcome to ___" heading.
The pictures are very eye catching and make you think! 
Nice intro page!

**Comment by evt632** [comment]
on BMI page: How are we going to start **working** your BMI to that healthy range? Could this be "moving" instead?
love the interactive BMI page!
on Cardio page: vigorous-intensity .  Why is there a hyphen here?
on Cardio page: throughout the day *_You want to gradually progress your exercise time, frequency and intensity *_    **Needs periods  
on Cardio page Nice graphics!
Cool portion distortion graphic!

**Comment by mastersinsttech** [comment]
Welcome page done

**Comment by mastersinsttech** [comment]
bmi working changed to moving

**Comment by mastersinsttech** [comment]
grammar fixes on cardio page complete

**Comment by mastersinsttech** [comment]
Eric- please css Style <strong> to your liking I have updated for welcome page and will update all others.  obviously not in captions though.

**Comment by mastersinsttech** [comment]
ha ha when i typed--- strong---- with the brackets around it it just made everything that followed bold.

**Comment by evt632** [comment]
CSS has been styled. 

RESOLVED

**Comment by dukyba** [comment]
Done
