### ISSUE TITLE
Image on Calories page

### ISSUE THREAD

**Issue by mastersinsttech** [LKMcManus/commit-to-be-fit#65]
I would like to read the words on the Proportion vs Distortion.  They are small and almost blurry.

Using Internet Explorer

**Comment by evt632** [comment]
Need URL of Website containing image

**Comment by mastersinsttech** [comment]
http://www.bewellbarroncounty.org/portion-distortion-quiz/
I added this link to reference page already
here you go eric

**Comment by mastersinsttech** [comment]
http://www.skinnymom.com/6-ways-to-use-your-hands-to-eat-the-right-amount/portioncontrol/

here is the web site for the hand portion control image as well.
I added it to reference page

**Comment by evt632** [comment]
Images have been hyperlinked and titles have been updated on images to indicate to click to see the original.

RESOLVED

**Comment by dukyba** [comment]
Done
