### ISSUE TITLE
Commit to be Fit - content 

### ISSUE THREAD

**Issue by evt632** [LKMcManus/commit-to-be-fit#7]
in description it mentions finding ways to fit working out/losing weight into life module 2 is not as strong on how to loose weight check all links in modules to see if they help people find ways to fit working out into schedule.  Check module 3 because it has too many links

**Comment by evt632** [comment]
In "strength training"  to "checkpoint" navigation jumps.
Strength training page talks about stretching techniques.  Maybe that could be better put in the beginning of the fitness section and at the end.
Eating small and often can cause tooth decay.  Maybe that's not a good idea, but if you lose your teeth, that can aid in weight loss. :)
Wow!  I can see you did a lot of work on your project already!  Great job!  Looks like a great website on how to lose weight and stay healthy.

**Comment by dukyba** [comment]
Module 3 will have proper gating after the storyboard and will not appear as long as it is.
