### ISSUE TITLE
Final Exam Link

### ISSUE THREAD

**Issue by evt632** [LKMcManus/commit-to-be-fit#71]
Only shows up from Module 4 which may be OK.

**Comment by mastersinsttech** [comment]
we want to move references under commit to be fit logo and where references used to be becomes the final exam navigation

**Comment by dukyba** [comment]
Is this still something that we want to do?

**Comment by evt632** [comment]
I think so. We were thinking of moving the references link to the bottom-left corner under the commit to be fit logo, and in it's place at the top, place a link for the final exam that shows up after all the other slides have been accessed.

**Comment by wysiwyg98** [comment]
I'll look at it, but it won't be ready for tomorrow.

**Comment by dukyba** [comment]
Nope. We decided not to do this one.
