### ISSUE TITLE
cardio or strength

### ISSUE THREAD

**Issue by evt632** [LKMcManus/commit-to-be-fit#72]
It wasn't immediately clear to me why there was not next button and that I was supposed to choose which route to take, perhaps have the choices at the bottom like you usually have the next button?

**Comment by mastersinsttech** [comment]
where the next and previous buttons are typically we want to add a Cardio and strength button

**Comment by evt632** [comment]
Buttons are made.

Body of text was removed.

I think we are ready to close

**Comment by dukyba** [comment]
Done
