### ISSUE TITLE
Intro image

### ISSUE THREAD

**Issue by evt632** [LKMcManus/commit-to-be-fit#76]
for the male I'm not certain what the image is trying to convey, its sort of small to see whats going on with the machines inside.  I'm assuming maybe its like your metabolism? But I can't tell if ones working better than the other or why one goes greyscale?

**Comment by mastersinsttech** [comment]
needs click to enlarge

**Comment by dukyba** [comment]
Are we going to make this image where it can be clicked?

**Comment by dukyba** [comment]
We disagree. Will be closing now.
