### ISSUE TITLE
Do we have to have a drag and drop page for compliance?

### ISSUE THREAD

**Issue by mastersinsttech** [LKMcManus/commit-to-be-fit#79]
Do we have to have a drag and drop page for compliance or is the hot spot we have in cardio module meet the requirement?

**Comment by mastersinsttech** [comment]
I meant hot spot in module 4

**Comment by dukyba** [comment]
I think we just need one or the other.

**Comment by LKMcManus** [comment]
I looked on the final project requirements and it does not specify a number of interactivities required. it just says "interactivity (e.g. hot spots, drag and drops)". I think we can close this one.

**Comment by dukyba** [comment]
We have the hover and that meets the requirements.
