### ISSUE TITLE
Am I the only one still getting a different look and font on RANGE OF MOTION page?

### ISSUE THREAD

**Issue by mastersinsttech** [LKMcManus/commit-to-be-fit#80]

**Comment by dukyba** [comment]
I am also getting it. Everything is bigger in Firefox.

**Comment by dukyba** [comment]
This should be fixed now. 
For some reason </header> was missing from line 12 and that was making everything look off.

**Comment by dukyba** [comment]
Will close once someone else and verify.

**Comment by dukyba** [comment]
Fixed
